# Generated by Django 5.2 on 2025-04-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_subdivision_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='city',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
    ]
