# Generated by Django 5.1.7 on 2025-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_subdivision_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6),
        ),
    ]
