# Generated by Django 5.1.7 on 2025-04-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='image',
        ),
        migrations.CreateModel(
            name='SubdivisionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='subdivisions/images/')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapp.subdivision')),
            ],
        ),
    ]
