# Generated by Django 5.1.7 on 2025-04-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_subdivision_image_subdivisionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='subdivisions/'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='subdivisions/'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='subdivisions/'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='subdivisions/'),
        ),
        migrations.DeleteModel(
            name='SubdivisionImage',
        ),
    ]
