# Generated by Django 5.1.7 on 2025-04-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_subdivision_image1_subdivision_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission in %', max_digits=5),
        ),
    ]
