# Generated by Django 5.1.7 on 2025-05-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_subdivision_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='memos/')),
                ('description', models.TextField()),
                ('when', models.DateTimeField()),
                ('where', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
