# Generated by Django 5.1.7 on 2025-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_memoreadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='file',
            field=models.FileField(null=True, upload_to='memos/'),
        ),
    ]
