# Generated by Django 5.1.7 on 2025-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_memo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='memos/'),
        ),
    ]
