# Generated by Django 5.1.7 on 2025-05-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_subdivision_construction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location details', max_length=255, null=True),
        ),
    ]
