# Generated by Django 5.1.7 on 2025-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_subdivision_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='house_model',
            field=models.CharField(blank=True, help_text='Optional house model description', max_length=255, null=True),
        ),
    ]
