# Generated by Django 5.1.7 on 2025-05-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_subdivision_house_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('RFO', 'Ready For Occupancy'), ('Preselling', 'Preselling')], max_length=10, null=True),
        ),
    ]
