# Generated by Django 5.2.1 on 2025-05-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_profile_reset_token_profile_reset_token_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivision',
            name='house_model',
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=50)),
                ('lot_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_models', to='webapp.subdivision')),
            ],
        ),
    ]
