# Generated by Django 5.2.1 on 2025-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_remove_subdivision_house_model_housemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='lot_area',
        ),
    ]
