# Generated by Django 5.1.7 on 2025-05-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_remove_housemodel_floor_remove_housemodel_lot_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='house_model',
            field=models.CharField(blank=True, help_text='Optional house model description', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='HouseModel',
        ),
    ]
